### ISSUE TITLE
How to use my  own dataset for training

### ISSUE THREAD

**Issue by shanshanhuang2023** [IvanXie416/IFNet#1]
Hello author, thank you very much for your outstanding work. I now want to use my own dataset for training and visualization. Could you give me some advice?

**Comment by IvanXie416** [comment]
If your data is similar to modelnet40 or 7scenes, you can test it directly with the corresponding pre-trained model, otherwise you need to refer to data/dataset.py to rewrite the corresponding classes.

**Comment by shanshanhuang2023** [comment]
Thanks for your reply! And If I want to visualize the point cloud registration, do I need to write the relevant visualization code myself, because I see that the released code does not provide it?
